#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CssDupFinder.Templates
{
    using System;
    using System.Collections.Generic;
    
    #line 6 "..\..\Templates\CssFileReportTemplate.cshtml"
    using System.IO;
    
    #line default
    #line hidden
    using System.Linq;
    using System.Text;
    
    #line 3 "..\..\Templates\CssFileReportTemplate.cshtml"
    using CssDupFinder.Models;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Templates\CssFileReportTemplate.cshtml"
    using CssDupFinder.Templates;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Templates\CssFileReportTemplate.cshtml"
    using DiffPlex.DiffBuilder.Model;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class CssFileReportTemplate : TemplateBaseWriter<CssFileReportModel>
    {
#line hidden

        #line 10 "..\..\Templates\CssFileReportTemplate.cshtml"

    public CssFileReportTemplate(TextWriter writer, CssFileReportModel model): base(writer, model) {}

        #line default
        #line hidden
#line hidden
public System.Web.WebPages.HelperResult DiffLine(DiffPiece line)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 15 "..\..\Templates\CssFileReportTemplate.cshtml"
 
    var spaceValue = "\u00B7";
    var tabValue = "\u00B7\u00B7";

    if (line.Type == ChangeType.Deleted || line.Type == ChangeType.Inserted || line.Type == ChangeType.Unchanged)
    {
        
#line default
#line hidden


#line 21 "..\..\Templates\CssFileReportTemplate.cshtml"
WriteTo(@__razor_helper_writer, line.Text.Replace(" ", spaceValue).Replace("\t", tabValue));

#line default
#line hidden


#line 21 "..\..\Templates\CssFileReportTemplate.cshtml"
                                                                     
    }
    else if (line.Type == ChangeType.Modified)
    {
        foreach (var character in line.SubPieces)
        {
            if (character.Type != ChangeType.Imaginary)
            {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                <span class=\"");



#line 29 "..\..\Templates\CssFileReportTemplate.cshtml"
WriteTo(@__razor_helper_writer, character.Type);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "Character\">\r\n                    ");



#line 30 "..\..\Templates\CssFileReportTemplate.cshtml"
WriteTo(@__razor_helper_writer, character.Text.Replace(" ", spaceValue.ToString()));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\r\n                </span>\r\n");



#line 32 "..\..\Templates\CssFileReportTemplate.cshtml"
            }
        }
    }

#line default
#line hidden

});

}

#line hidden
public System.Web.WebPages.HelperResult DiffPane(DiffPaneModel pane)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 38 "..\..\Templates\CssFileReportTemplate.cshtml"
 

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <div class=\"diffPane\">\r\n        <table cellpadding=\"0\" cellspacing=\"0\" class=" +
"\"diffTable\">\r\n");



#line 41 "..\..\Templates\CssFileReportTemplate.cshtml"
             foreach (var line in pane.Lines)
            {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                <tr>\r\n                    <td class=\"lineNumber\">");



#line 44 "..\..\Templates\CssFileReportTemplate.cshtml"
             WriteTo(@__razor_helper_writer, line.Position.HasValue ? line.Position.GetValueOrDefault().ToString() : "&nbsp;");

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</td>\r\n                    <td class=\"line");



#line 45 "..\..\Templates\CssFileReportTemplate.cshtml"
     WriteTo(@__razor_helper_writer, line.Type);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "Line\">\r\n                        <span class=\"lineText\">\r\n");



#line 47 "..\..\Templates\CssFileReportTemplate.cshtml"
                             if (!String.IsNullOrEmpty(line.Text))
                            {
                                
#line default
#line hidden


#line 49 "..\..\Templates\CssFileReportTemplate.cshtml"
 WriteTo(@__razor_helper_writer, DiffLine(line));

#line default
#line hidden


#line 49 "..\..\Templates\CssFileReportTemplate.cshtml"
                                               
                            }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                        </span>\r\n                    </td>\r\n                </tr>" +
"\r\n");



#line 54 "..\..\Templates\CssFileReportTemplate.cshtml"
            }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "        </table>\r\n    </div>\r\n");



#line 57 "..\..\Templates\CssFileReportTemplate.cshtml"

#line default
#line hidden

});

}


        public override void Execute()
        {


WriteLiteral("\r\n\r\n");





WriteLiteral("\r\n");


WriteLiteral("\r\n");


WriteLiteral("\r\n\r\n");



WriteLiteral("\r\n\r\n");



WriteLiteral(@"

<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 Transitional//EN"" ""http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"">

<html xmlns=""http://www.w3.org/1999/xhtml"">
<head>
    <meta http-equiv=""Content-Type"" content=""text/html; charset=iso-8859-1"" />
    <title>Duplicate Finder</title>
    <link href=""css/main.css"" rel=""stylesheet"" type=""text/css"" />
    <link href=""css/diff.css"" rel=""stylesheet"" type=""text/css"" />
</head>
<body>
    <div id=""mainContent"">
        <div id=""resume"">
            <h1> Resumo </h1>
            <div>");


            
            #line 72 "..\..\Templates\CssFileReportTemplate.cshtml"
             Write("Arquivo: ");

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 72 "..\..\Templates\CssFileReportTemplate.cshtml"
                           Write(Model.FileFullPath);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n            <div>");


            
            #line 73 "..\..\Templates\CssFileReportTemplate.cshtml"
             Write("Total de seletores: ");

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 73 "..\..\Templates\CssFileReportTemplate.cshtml"
                                      Write(Model.TotalSelectors);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n            <div>");


            
            #line 74 "..\..\Templates\CssFileReportTemplate.cshtml"
             Write("Total de seletores duplicados: ");

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 74 "..\..\Templates\CssFileReportTemplate.cshtml"
                                                 Write(Model.TotalDuplicates);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n            <div>");


            
            #line 75 "..\..\Templates\CssFileReportTemplate.cshtml"
             Write("Duplicados no arquivo: ");

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 75 "..\..\Templates\CssFileReportTemplate.cshtml"
                                         Write(Model.DuplicatePercentage);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n        </div>\r\n\r\n");


            
            #line 78 "..\..\Templates\CssFileReportTemplate.cshtml"
         foreach (var block in Model.Blocks)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"diffBox\">\r\n                <div>");


            
            #line 81 "..\..\Templates\CssFileReportTemplate.cshtml"
                 Write(block.CountDuplicates);

            
            #line default
            #line hidden

            
            #line 81 "..\..\Templates\CssFileReportTemplate.cshtml"
                                         Write("  duplicados.");

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n                <div id=\"leftPane\">\r\n                    <div class=\"di" +
"ffHeader\">Old Text</div>\r\n                    ");


            
            #line 85 "..\..\Templates\CssFileReportTemplate.cshtml"
               Write(DiffPane(block.Diff.OldText));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div id=\"rightPane\">\r\n                 " +
"   <div class=\"diffHeader\">New Text</div>\r\n                    ");


            
            #line 89 "..\..\Templates\CssFileReportTemplate.cshtml"
               Write(DiffPane(block.Diff.NewText));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div class=\"clear\"></div>\r\n            " +
"</div>\r\n");


            
            #line 93 "..\..\Templates\CssFileReportTemplate.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral(@"    </div>

    <script type=""text/javascript"" src=""js/jquery-1.4.1.min.js""></script>
    <script type=""text/javascript"" src=""js/diff.js""></script>

    <script type=""text/javascript"">
        $(function () {
            InitializeDiffPanes();
        });
    </script>
</body>
</html>");


        }
    }
}
#pragma warning restore 1591
