#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CssDupFinder.Templates
{
    using System;
    using System.Collections.Generic;
    
    #line 5 "..\..\Templates\DashboardReportTemplate.cshtml"
    using System.IO;
    
    #line default
    #line hidden
    using System.Linq;
    using System.Text;
    
    #line 3 "..\..\Templates\DashboardReportTemplate.cshtml"
    using CssDupFinder.Models;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Templates\DashboardReportTemplate.cshtml"
    using CssDupFinder.Templates;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class DashboardReportTemplate : TemplateBaseWriter<DashboardReportModel>
    {
#line hidden

        #line 9 "..\..\Templates\DashboardReportTemplate.cshtml"

    public DashboardReportTemplate(TextWriter writer, DashboardReportModel model): base(writer, model) {}

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n\r\n");




WriteLiteral("\r\n");


WriteLiteral("\r\n");


WriteLiteral(@"

<!DOCTYPE html PUBLIC ""-//W3C//DTD XHTML 1.0 Transitional//EN"" ""http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"">

<html xmlns=""http://www.w3.org/1999/xhtml"">
<head>
    <meta http-equiv=""Content-Type"" content=""text/html; charset=iso-8859-1"" />
    <title>Duplicate Finder</title>
    <link href=""css/main.css"" rel=""stylesheet"" type=""text/css"" />
    <link href=""css/diff.css"" rel=""stylesheet"" type=""text/css"" />
</head>
<body>
    <div id=""mainContent"">
        <div id=""resume"">
            <h1>Resumo </h1>       
            <div>");


            
            #line 26 "..\..\Templates\DashboardReportTemplate.cshtml"
             Write("Total de seletores: ");

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 26 "..\..\Templates\DashboardReportTemplate.cshtml"
                                      Write(Model.TotalSelectors);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n            <div>");


            
            #line 27 "..\..\Templates\DashboardReportTemplate.cshtml"
             Write("Total de seletores duplicados: ");

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 27 "..\..\Templates\DashboardReportTemplate.cshtml"
                                                 Write(Model.TotalDuplicated);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n            <div>");


            
            #line 28 "..\..\Templates\DashboardReportTemplate.cshtml"
             Write("Duplicados no arquivo: ");

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 28 "..\..\Templates\DashboardReportTemplate.cshtml"
                                          Write(Model.DuplicatePercentage);

            
            #line default
            #line hidden
WriteLiteral("%</div>\r\n        </div>\r\n        <div>\r\n            <h1>Files</h1>\r\n            <" +
"div class=\"pages\">\r\n");


            
            #line 33 "..\..\Templates\DashboardReportTemplate.cshtml"
                 foreach (var link in Model.Links)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <a href=\"");


            
            #line 35 "..\..\Templates\DashboardReportTemplate.cshtml"
                        Write(link);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 35 "..\..\Templates\DashboardReportTemplate.cshtml"
                               Write(Path.GetFileNameWithoutExtension(link));

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");


            
            #line 36 "..\..\Templates\DashboardReportTemplate.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </div>\r\n    </div>\r\n</body>\r\n</html>");


        }
    }
}
#pragma warning restore 1591
